spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_manage_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: yzj
    password: yzj_admin
  web:
    resources:
      static-locations: classpath:/static/
server:
  tomcat:
    max-http-form-post-size: 10MB